"""
Django settings for agl_colo_report project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

NAME_DATA_DIR = "data"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR_ORGAN = os.path.join(BASE_DIR, NAME_DATA_DIR, 'organ')
DATA_DIR_ANASTOMOSIS = os.path.join(BASE_DIR, NAME_DATA_DIR, 'anastomosis')
DATA_DIR_COLON_ANATOMY = os.path.join(BASE_DIR, NAME_DATA_DIR, 'colon-anatomy')
DATA_DIR_INFORMATION_SOURCE = os.path.join(BASE_DIR, NAME_DATA_DIR, 'information-source')
DATA_DIR_PATHOLOGY_TYPE = os.path.join(BASE_DIR, NAME_DATA_DIR, 'pathology-type')
DATA_DIR_UNIT = os.path.join(BASE_DIR, NAME_DATA_DIR, 'unit')
DATA_DIR_DRUG = os.path.join(BASE_DIR, NAME_DATA_DIR, 'drug')
DATA_DIR_MORPHOLOGY = os.path.join(BASE_DIR, NAME_DATA_DIR, 'morphology')
DATA_DIR_SIZE = os.path.join(BASE_DIR, NAME_DATA_DIR, 'size')
DATA_DIR_INTERVENTION = os.path.join(BASE_DIR, NAME_DATA_DIR, 'intervention')
DATA_DIR_INSTRUMENT = os.path.join(BASE_DIR, NAME_DATA_DIR, 'instrument')
DATA_DIR_COMPLICATION = os.path.join(BASE_DIR, NAME_DATA_DIR, 'complication')
DATA_DIR_EXAMINATION = os.path.join(BASE_DIR, NAME_DATA_DIR, 'examination')
DATA_DIR_INDICATION = os.path.join(BASE_DIR, NAME_DATA_DIR, 'indication')

LOG_DIR = os.path.join(BASE_DIR, 'logs')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)=nhf+8!cls8d=rg&_m2_$%hrx+49vlep(51+fxw(syv82njbz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "bootstrap4",
    "reports",
    "logger",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agl_colo_report.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agl_colo_report.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


