# Generated by Django 4.2.5 on 2023-09-25 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anastomosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_de', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnastomosisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColonAnatomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_de', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('available_anastomoses', models.ManyToManyField(blank=True, related_name='available_in_anatomies', to='reports.anastomosis')),
            ],
        ),
        migrations.CreateModel(
            name='InformationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('components_ordered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrganComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('component_order_id', models.IntegerField(blank=True, null=True)),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='reports.organ')),
            ],
        ),
        migrations.CreateModel(
            name='PathologyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PolypMorphology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_procedure', models.DateField(default=django.utils.timezone.now)),
                ('altered_colon_anatomy', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='no', max_length=10)),
                ('colon_anatomy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.colonanatomy')),
                ('deepest_insertion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.organcomponent')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Premedication',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='premedication', serialize=False, to='reports.report')),
                ('blood_oxygen_monitoring', models.BooleanField(default=True)),
                ('blood_pressure_monitoring', models.BooleanField(default=True)),
                ('ecg_monitoring', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('preferred_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ColonPolyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('pathology_types', models.ManyToManyField(related_name='colon_polyps', to='reports.pathologytype')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polyps', to='reports.report')),
            ],
        ),
        migrations.AddField(
            model_name='colonanatomy',
            name='available_segments',
            field=models.ManyToManyField(related_name='available_in_anatomies', to='reports.organcomponent'),
        ),
        migrations.AddField(
            model_name='anastomosis',
            name='component_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component1_anastomoses', to='reports.organcomponent'),
        ),
        migrations.AddField(
            model_name='anastomosis',
            name='component_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component2_anastomoses', to='reports.organcomponent'),
        ),
        migrations.AddField(
            model_name='anastomosis',
            name='connection_type_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection1_anastomoses', to='reports.anastomosistype'),
        ),
        migrations.AddField(
            model_name='anastomosis',
            name='connection_type_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection2_anastomoses', to='reports.anastomosistype'),
        ),
        migrations.CreateModel(
            name='DrugApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.drug')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.unit')),
                ('premedication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_applications', to='reports.premedication')),
            ],
        ),
        migrations.CreateModel(
            name='ColonPolypMorphology',
            fields=[
                ('polyp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='morphology', serialize=False, to='reports.colonpolyp')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('morphology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.polypmorphology')),
            ],
        ),
        migrations.CreateModel(
            name='ColonPolypLocation',
            fields=[
                ('polyp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='location', serialize=False, to='reports.colonpolyp')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('cm', models.IntegerField(blank=True, null=True)),
                ('anastomosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polyp_locations', to='reports.anastomosis')),
                ('colon_anatomy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polyp_locations', to='reports.colonanatomy')),
                ('organ_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polyp_locations', to='reports.organcomponent')),
            ],
        ),
    ]
