# Generated by Django 4.2.5 on 2023-09-25 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colonpolyplocation',
            name='colon_anatomy',
        ),
        migrations.RemoveField(
            model_name='colonpolypmorphology',
            name='morphology',
        ),
        migrations.AlterField(
            model_name='colonpolyplocation',
            name='polyp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='colon_polyp_location', serialize=False, to='reports.colonpolyp'),
        ),
        migrations.AlterField(
            model_name='report',
            name='colon_anatomy',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.colonanatomy'),
        ),
        migrations.CreateModel(
            name='SizeMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.unit')),
            ],
        ),
        migrations.CreateModel(
            name='SizeClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('pathology_types', models.ManyToManyField(blank=True, related_name='size_classifications', to='reports.pathologytype')),
            ],
        ),
        migrations.CreateModel(
            name='SizeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('size_min', models.FloatField()),
                ('size_max', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('size_classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_categories', to='reports.sizeclassification')),
                ('size_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.unit')),
            ],
        ),
        migrations.CreateModel(
            name='MorphologyClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('pathology_types', models.ManyToManyField(blank=True, related_name='morphology_classifications', to='reports.pathologytype')),
            ],
        ),
        migrations.CreateModel(
            name='MorphologyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='reports.morphologyclassification')),
            ],
        ),
        migrations.CreateModel(
            name='ColonPolypSize',
            fields=[
                ('polyp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='size', serialize=False, to='reports.colonpolyp')),
                ('size_categorical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colon_polyps_categorical', to='reports.sizecategory')),
                ('size_measurement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colon_polyp_size', to='reports.sizemeasurement')),
                ('size_paris', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colon_polyps_paris', to='reports.sizecategory')),
            ],
        ),
        migrations.AddField(
            model_name='colonpolypmorphology',
            name='morphology_categorical',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='colon_polyps_categorical', to='reports.morphologycategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colonpolypmorphology',
            name='morphology_paris',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='colon_polyps_paris', to='reports.morphologycategory'),
            preserve_default=False,
        ),
    ]
