# Generated by Django 4.2.5 on 2023-09-30 13:06

from django.db import migrations, models
import django.db.models.deletion
import reports.models.report


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugapplication',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='colon_anatomy',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.colonanatomy'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_of_procedure',
            field=models.DateField(default=reports.models.report.get_current_date),
        ),
    ]
