# Generated by Django 4.2.5 on 2023-09-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_drugapplication_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonpolypmorphology',
            name='categorical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colon_polyps_categorical', to='reports.morphologycategory'),
        ),
        migrations.AlterField(
            model_name='colonpolypmorphology',
            name='paris',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colon_polyps_paris', to='reports.morphologycategory'),
        ),
    ]
