# Generated by Django 4.2.5 on 2023-09-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_colonpolyplocation_colon_anatomy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sizecategory',
            old_name='size_classification',
            new_name='classification',
        ),
        migrations.RenameField(
            model_name='sizecategory',
            old_name='size_unit',
            new_name='unit',
        ),
    ]
