# Generated by Django 4.2.5 on 2023-09-30 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_colonpolypmorphology_categorical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfindings',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='reports.report'),
        ),
    ]
