# Generated by Django 4.2.5 on 2023-09-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_reportfindings_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colonpolyplocation',
            old_name='cm',
            new_name='cm_from_anal_verge',
        ),
    ]
