# Generated by Django 4.2.5 on 2023-09-30 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_rename_cm_colonpolyplocation_cm_from_anal_verge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonpolyplocation',
            name='polyp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='location', serialize=False, to='reports.colonpolyp'),
        ),
    ]
