# Generated by Django 4.2.5 on 2023-09-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_interventionmanager_intervention_pathology_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='intervention_types',
            field=models.ManyToManyField(related_name='interventions', to='reports.interventiontype'),
        ),
    ]
