# Generated by Django 4.2.5 on 2023-09-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_rename_instrument_type_instrument_instrument_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='indication',
            name='indication_types',
            field=models.ManyToManyField(blank=True, to='reports.indicationtype'),
        ),
    ]
