# Generated by Django 4.2.5 on 2023-09-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_indication_indication_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complication',
            name='complication_type',
        ),
        migrations.AddField(
            model_name='complication',
            name='complication_types',
            field=models.ManyToManyField(blank=True, to='reports.complicationtype'),
        ),
    ]
