# Generated by Django 4.2.5 on 2023-09-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_examinationtime_examinationtimetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationtime',
            name='examination_time_types',
            field=models.ManyToManyField(blank=True, to='reports.examinationtimetype'),
        ),
    ]
