# Generated by Django 4.2.5 on 2023-09-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_examinationtime_examination_time_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examinationtime',
            old_name='examination_time_types',
            new_name='time_types',
        ),
    ]
